<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    public function comment($id){

        $qb = $this->createQueryBuilder('c');

        $query=$qb
            ->where('c.id=:id')
            ->setParameter('id', $id) ;

        $result = $query->getQuery()->execute();

        return $result ;


    }
}
